### ISSUE TITLE
missing build file?

### ISSUE THREAD

**Issue by rmackay9** [yankailab/OpenKAI#10]
There's a broken link in the README.md file in the "Build & Run" section.

broken link: https://github.com/yankailab/OpenKAI/blob/master/doc/JetsonTX1/build.md

This was reported by @SteveJos in the ArduPilot/VisionProjects gitter chat: https://gitter.im/ArduPilot/VisionProjects

**Comment by k5un** [comment]
Hi Randy. The docs are moved to http://www.openkai.xyz/. You may find it from there. Cheers.
