### ISSUE TITLE
Using Single Shot Detector (SSD) with a MIPI (leopard imaging) camera on a TX1

### ISSUE THREAD

**Issue by pnambiar** [yankailab/OpenKAI#15]
Here is what I have so far:

 1) Removed Opencv4tegra
 2) Installed Opencv 3.1 on TX1 (Had problem installing Caffe with 3.2, hence 3.1!)
 3) Got the image grabber working with opencv (python). Here is the VideoCapture input:

 cap = cv2.VideoCapture("nvcamerasrc ! video/x-raw(memory:NVMM), width=(int)192, height=(int)1080,format-(string)I420,framerate=(fraction)30/1 ! nvvidconv flip-method=0 ! video/x-raw, format=(string)BGRx ! videoconvert ! video/x-raw, format=(string)BGR ! appsink")

 4) Installed SSD

 Now, how do I input the device ID to ssd_pascal_webcam.py?

 Any leads will be appreciated. Thanks in advance!

**Comment by yankailab** [comment]
Hi pnambiar, is ssd_pascal_webcam part of OpenKAI? anyway, you can simple do
cap = cv2.VideoCapture(0)
to get input from /dev/video0

**Comment by pnambiar** [comment]
Tried. That does not work
