### ISSUE TITLE
Problems flashing image to TX1

### ISSUE THREAD

**Issue by skeyang** [yankailab/OpenKAI#16]
I'm still new at all this and I need some help for this issue. I'm having problems flashing the apsync-tx1-openkai image from firmware.ardupilot.org into the TX1. While setting up the TX1 as companion computer I followed the instructions in ardupilot and I successfully downloaded JetPack 2.3.1 and flashed the official TX1 image. However when I tried to flash the apsync-tx1-openkai image it kept showing "USB communication failed. Check if device is in recovery", I typed "lsusb" in the terminal and it shows "ID 0955:7721 NVidia Corp." so I know that the device is in recovery mode.  Has anyone encountered this problem as well?

**Comment by yankailab** [comment]
Hi skeyang, yes it happened to me also and I solved it by switching to another USB port on my host pc, make sure not to use any USB hub between the host and TX1. Use USB 2.0 port instead of 3.0, if you have one.
