### ISSUE TITLE
about m_vQ in ORB_SLAM2

### ISSUE THREAD

**Issue by janboeye** [yankailab/OpenKAI#18]
hi,

I saw pose get in detect() of _ORB_SLAM2, but no one uses this pose. Am I correct?

Thanks a lot!

**Comment by yankailab** [comment]
hello, the quarternion is going to be sent to flight controller (ArduCopter). Currently we are working together on the integrations.

**Comment by janboeye** [comment]
@yankailab the quarternion is planned to be used by controller to correct IMU data or other purpose?

Thanks

**Comment by yankailab** [comment]
There is a new message available in AC that is going to use the quartenion:
https://github.com/rmackay9/mavlink/commit/8e9e6f1cb508b63bab783652da93acbc34381173
