### ISSUE TITLE
about DNNAvoid

### ISSUE THREAD

**Issue by janboeye** [yankailab/OpenKAI#19]
hi,

Why mavlink is commented out in  inAPcopter_DNNavoid::update? which class implement the avoid function, DDNAvoid or SensorAvoid?

Thanks

**Comment by yankailab** [comment]
hello, currently SensorAvoid works with ZED camera, while DNNAvoid is being implemented and not working yet. SensorAvoid is using stereo camera (depth map) to for collision avoidance, on the other hand, DNNAvoid is planned to recognize the scene based on neural network (DNN implemented by caffe or TensorRT) and make decisions like go, stop, turn left/right and etc.
