### ISSUE TITLE
Shorten output from VISION_POSITION_ESTIMATE

### ISSUE THREAD

**Issue by peterbarker** [yankailab/OpenKAI#24]
The output lines are way too long, and difficult to parse as they fly by.

Use 0-padding and length-specification in format strings to make output more consistent and shorten text so lines are a reasonable length:

e.g.
`VISION_POSITION_DELTA dt=%u vx=%03.05f vy=%03.05f vz=%03.05f r=%03.05f p=%03.05f y=%03.05f cnf=%u`

**Comment by yankailab** [comment]
Updated to new interface using ncurses by default,
{
	"name":"APP",
        "bLog":0,   /* 0: ncurses based console, 1: use old log style */
}
