### ISSUE TITLE
404 ERROR！！！These links didn't exist. How can I get new websites？

### ISSUE THREAD

**Issue by xuwumin** [yankailab/OpenKAI#27]
[Build on Ubuntu desktop systems](url)
[###Build on NVIDIA Jetson TX1](url)

**Comment by yankailab** [comment]
Hi please refer to
docs.openkai.xyz
for the latest documents, and install script for TX2 tested on JetPack 3.2
https://github.com/yankailab/OpenKAI/blob/master/sh/Install/OpenKAI_install_TX2.sh
