### ISSUE TITLE
希望这个系统添加双目摄像头支持

### ISSUE THREAD

**Issue by cudnn** [yankailab/OpenKAI#28]
我看了以前的历史版本，这个系统以前是支持双目摄像头的-cudastero模块！但是后来可能考虑到性能和运算量问题删掉了！
目前zed cam 和inter realsensor 成本比较高，而且摄像头间距很小，深度探测距离很近，大约只有20m或更低。
我们自己设计了间距为40cm到80cm的大间距 同步usb3.0 uvc摄像头，以满足50到100米深度探测需求，主要用于固定翼飞机和无人车自动驾驶。这样基本可以替代激光雷达。
并且做了便携式计算机 i5+gtx960m，或者i5+gtx1060,满足运算需求。
希望这个系统加入对这种摄像头的支持，完成orb slam计算和双目立体深度计算，实现ardupilot 定位 定姿态 避障和路径规划功能

**Comment by yankailab** [comment]
Hi我们在不断寻找和支持新的device，请问您的双目摄像头是否有产品介绍的链接可参考？

**Comment by cudnn** [comment]
你需要的话我给你寄过几个去，我先给你发个链接

**Comment by cudnn** [comment]
我这几天认真关注了你的这个系统，感觉用mavros实现非常简单 各种驱动也很多

**Comment by cudnn** [comment]
这个是mavros 外部地位辅助定位的简介，你看看https://github.com/PX4/Devguide/blob/master/en/ros/external_position_estimation.md

**Comment by cudnn** [comment]
这是摄像头链接 【130万双目高清USB电脑台式摄像头双画面同步拍摄高速60帧可调基线】http://m.tb.cn/h.WDEAdcY 点击链接，再选择浏览器打开；或复制这条信息￥6y2m0IGRhZu￥后打开👉手淘👈

**Comment by cudnn** [comment]
我们还有另一种usb 3.0 全局曝光基线可调的 带陀螺和加速度的双目摄像头，在小批量生产，基本是参考百度的，我发链接给你

**Comment by cudnn** [comment]
https://github.com/rangj/fx3eyes

**Comment by yankailab** [comment]
Hi, somehow I couldn't open the link you provided before, do you have other references available?
