### ISSUE TITLE
x86平台编译遇到好多问题，yankailab看看有没有更好的解决方法，这是CMakeLists.txt的问题

### ISSUE THREAD

**Issue by cudnn** [yankailab/OpenKAI#33]
1.修改显卡的运算能力 set(CUDA_ARCH "50" CACHE STRING "")
2.SLAM、DARKNET、jetson-inference-batch几个库放在/home/user下要写完整目录，不然会找不到 "cudaMappedMemory.h"、"cudaNormalize.h"、"detectNet.h"、"imageNet.h"等文件。
3.  set(OpenKAI_include ${OpenKAI_include} "${ORB_SLAM2_root}  ${ORB_SLAM2_root}/include ${Pangolin_INCLUDE_DIRS}") 要分开写，
 set(OpenKAI_include ${OpenKAI_include} "${ORB_SLAM2_root} ")
  set(OpenKAI_include ${OpenKAI_include} "${ORB_SLAM2_root}/include")
  set(OpenKAI_include ${OpenKAI_include} "${Pangolin_INCLUDE_DIRS}")
不然会找不到 {ORB_SLAM2_root}/include目录下的system.h。

**Comment by yankailab** [comment]
Hi there, CMakeList.txt is updated, please also refer to https://github.com/yankailab/OpenKAI/blob/master/sh/Setup/OpenKAI_dev_setup.sh
for the environment setup.
Cheers.

**Comment by yankailab** [comment]
Now we use ORB_SLAM3, you can find the setup here:
https://github.com/yankailab/OpenKAI/blob/037250ccd8614f068900a7ca18ac3c82c5879b42/sh/Setup/OpenKAI_dev_setup.sh#L252

CMakeList.txt is also updated accordingly, now you can turn on the USE_ORB_SLAM in CMake and it should work.
