### ISSUE TITLE
SegNet It displays a single class.

### ISSUE THREAD

**Issue by montekristo1946** [yankailab/OpenKAI#6]
I use your class SegNet.cpp. 
Method -  void _SegNet::segment(void)  
line - Mat segIdx = Mat(m_InputSize.height, m_InputSize.width, CV_32FC1, (void*)begin); Gets an array of the correct structure, but all weekend classes are equal to 0.
Please tell me what could be wrong?

**Comment by yankailab** [comment]
By "weekend classes" do you mean the "segmented classes" ?

**Comment by montekristo1946** [comment]
Hello. I use the model СamVid (segnet_inference.prototxt) trained at its examples. The resulting file weights normally runs on Python script.
In your code, after receiving a pointer to the output:
`const float * begin = output_layer-> cpu_data ();`
just get the output matrix:
`Mat segIdx = Mat (m_InputSize.height, m_InputSize.width, CV_32FC1, (void *) begin);`
I think segIdx contains only first class.
How to get the maximum output in all layers?
