### ISSUE TITLE
ADD README.MD

### ISSUE THREAD

**Issue by aiilab** [yankailab/OpenKAI#8]
Hi. @yankailab. Thanks for your great work! I am running this code on my jetson tx1. But I have no idea how to start. Could you please add a detailed **README** file for instructions. thanks!

**Comment by yankailab** [comment]
Hi @AAAyag , thanks! will add readme soon. The setup procedure could take quite a time for Jetson TX1, if you would like to try it quickly on JetsonTX1 I recommend to flash this pre-built image:
https://drive.google.com/file/d/0B4dxluiaMPBOUDEzMENyaVRpX3c/view?usp=sharing

The flash command can be found here (Restoring image):
http://elinux.org/Jetson/TX1_Cloning

Once finished flashing, connect a USB webcam and start from terminal:
./OpenKAI.sh
and there you go.

Note: make sure to specify the correct /video# in the config file, for the above image it is stored in:
/home/ubuntu/src/OpenKAI/src/config.txt

Find the part:
	"name":"mainStream",
	"class":"_Stream",
...
	"input":"Generic",    //<--set to "Generic"

and verify:
	{
		"name":"Generic",
		"class":"Camera",
		"FPS":30,
		"ID":0,           //<--set to the correct index of your /dev/video#
		"width":1280,
		"height":720,
...
	}

**Comment by AAAyag** [comment]
Hi @yankailab . what's the fps on your tx1 with SSD object detetion? I tried SSD on Jetson TX1 and it worked with only 6-8 frames per second with the default python script for webcam. Maybe it can be optimized with tensorRT or other way. Did you try it to make it run faster?

**Comment by yankailab** [comment]
@aiilab probably we use different way of measuring the FPS of SSD, on my TX1 with the default FPS control in OpenKAI it measures ~3fps (SSD 300x300). With DetectNet (TensorRT, input size VGA) on TX1 it achieves ~15FPS.

**Comment by yankailab** [comment]
Readme added
