### ISSUE TITLE
How to build on Ubuntu 16.04

### ISSUE THREAD

**Issue by GPrathap** [yankailab/OpenKAI#9]
Under build and run session both links seem to be broken. 

 ###Build on NVIDIA Jetson TX1, ###Build on Ubuntu desktop systems

**Comment by k5un** [comment]
Hi there, it's been moved to www.openkai.xyz

**Comment by GPrathap** [comment]
Thanks, it worked. It would be better if readme linked to www.openkai.xyz. Please close this issue.
